//
// CalmLut.h - Auto-generated Look-Up Table for TOGGLE_CALM (Whelen DVI)
// Generated by generate_calm_lut.py (Size: 256, Gamma: 2.40, Max: 65535)
// DO NOT EDIT DIRECTLY - Use scripts/generate_calm_lut.py to re-generate.
//

#ifndef MAJAK_CALMLUT_H
#define MAJAK_CALMLUT_H

#include <stdint.h>

#define CALM_LUT_SIZE       256U
#define CALM_LUT_MAX_VALUE  65535U

static const uint16_t CALM_SINE_LUT[CALM_LUT_SIZE] = {
        0U,     9U,    47U,   125U,   249U,   424U,   655U,   945U,
     1297U,  1714U,  2197U,  2748U,  3367U,  4056U,  4813U,  5640U,
     6536U,  7499U,  8528U,  9622U, 10780U, 11997U, 13274U, 14606U,
    15990U, 17424U, 18903U, 20425U, 21985U, 23580U, 25204U, 26854U,
    28526U, 30214U, 31913U, 33619U, 35328U, 37033U, 38731U, 40416U,
    42083U, 43727U, 45343U, 46927U, 48474U, 49978U, 51436U, 52842U,
    54194U, 55486U, 56714U, 57875U, 58965U, 59981U, 60920U, 61778U,
    62553U, 63243U, 63846U, 64358U, 64780U, 65110U, 65346U, 65488U,
    65535U, 65488U, 65346U, 65110U, 64780U, 64358U, 63846U, 63243U,
    62553U, 61778U, 60920U, 59981U, 58965U, 57875U, 56714U, 55486U,
    54194U, 52842U, 51436U, 49978U, 48474U, 46927U, 45343U, 43727U,
    42083U, 40416U, 38731U, 37033U, 35328U, 33619U, 31913U, 30214U,
    28526U, 26854U, 25204U, 23580U, 21985U, 20425U, 18903U, 17424U,
    15990U, 14606U, 13274U, 11997U, 10780U,  9622U,  8528U,  7499U,
     6536U,  5640U,  4813U,  4056U,  3367U,  2748U,  2197U,  1714U,
     1297U,   945U,   655U,   424U,   249U,   125U,    47U,     9U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U
};

#endif // MAJAK_CALMLUT_H
