//
// CalmLut.h - Auto-generated Look-Up Table for TOGGLE_CALM (Whelen DVI)
// Generated by generate_calm_lut.py (Size: 256, Gamma: 2.20, ActiveRatio: 0.625, Max: 65535)
// DO NOT EDIT DIRECTLY - Use scripts/generate_calm_lut.py to re-generate.
//

#ifndef MAJAK_CALMLUT_H
#define MAJAK_CALMLUT_H

#include <stdint.h>

#define CALM_LUT_SIZE       256U
#define CALM_LUT_MAX_VALUE  65535U

static const uint16_t CALM_SINE_LUT[CALM_LUT_SIZE] = {
        0U,    12U,    53U,   129U,   242U,   396U,   590U,   827U,
     1107U,  1431U,  1799U,  2212U,  2670U,  3173U,  3720U,  4312U,
     4948U,  5628U,  6350U,  7114U,  7920U,  8766U,  9651U, 10574U,
    11534U, 12529U, 13559U, 14620U, 15713U, 16835U, 17985U, 19160U,
    20359U, 21580U, 22821U, 24080U, 25355U, 26644U, 27945U, 29255U,
    30573U, 31896U, 33222U, 34548U, 35873U, 37195U, 38510U, 39817U,
    41113U, 42397U, 43665U, 44917U, 46149U, 47359U, 48546U, 49707U,
    50841U, 51944U, 53017U, 54055U, 55059U, 56025U, 56953U, 57840U,
    58685U, 59487U, 60244U, 60954U, 61617U, 62232U, 62797U, 63311U,
    63773U, 64183U, 64540U, 64843U, 65091U, 65285U, 65424U, 65507U,
    65535U, 65507U, 65424U, 65285U, 65091U, 64843U, 64540U, 64183U,
    63773U, 63311U, 62797U, 62232U, 61617U, 60954U, 60244U, 59487U,
    58685U, 57840U, 56953U, 56025U, 55059U, 54055U, 53017U, 51944U,
    50841U, 49707U, 48546U, 47359U, 46149U, 44917U, 43665U, 42397U,
    41113U, 39817U, 38510U, 37195U, 35873U, 34548U, 33222U, 31896U,
    30573U, 29255U, 27945U, 26644U, 25355U, 24080U, 22821U, 21580U,
    20359U, 19160U, 17985U, 16835U, 15713U, 14620U, 13559U, 12529U,
    11534U, 10574U,  9651U,  8766U,  7920U,  7114U,  6350U,  5628U,
     4948U,  4312U,  3720U,  3173U,  2670U,  2212U,  1799U,  1431U,
     1107U,   827U,   590U,   396U,   242U,   129U,    53U,    12U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U,
        0U,     0U,     0U,     0U,     0U,     0U,     0U,     0U
};

#endif // MAJAK_CALMLUT_H
