//
// Created by Matouš Smékal on 04.09.2026.
//

#ifndef MAJAK_CANPROTOCOL_H
#define MAJAK_CANPROTOCOL_H

#define CAN_MASTER_ADDR 0x00
#define CAN_BROADCAST_ADDR 0xFF

#define CAN_PROTOCOL_OTA_DATA 0x00
#define CAN_PROTOCOL_DHCP 0x01
#define CAN_PROTOCOL_MASTER_OUT 0x02
#define CAN_PROTOCOL_SLAVE_OUT 0x03
#define CAN_PROTOCOL_TIME_SYNC 0x05

#define CAN_PROTOCOL_GET_LIGHTS 0x00
#define CAN_PROTOCOL_SET_LIGHTS 0x01
#define CAN_PROTOCOL_SET_BRIGHTNESS 0x02
#define CAN_PROTOCOL_GET_TAKEDOWNS 0x03
#define CAN_PROTOCOL_SET_TAKEDOWNS 0x04
#define CAN_PROTOCOL_ENTER_BOOT 0xFD

#define CAN_PROTOCOL_DHCP_DISCOVER 0x00
#define CAN_PROTOCOL_DHCP_OFFER 0x01
#define CAN_PROTOCOL_DHCP_ACK 0x02

#endif //MAJAK_CANPROTOCOL_H