//
// Created by Matouš Smékal on 04.09.2026.
//

#ifndef MAJAK_CANPROTOCOL_H
#define MAJAK_CANPROTOCOL_H

#define CAN_MASTER_ADDR 0x00
#define CAN_BROADCAST_ADDR 0xFF

#define CAN_PROTOCOL_OTA_DATA 0x00
#define CAN_PROTOCOL_DHCP 0x01
#define CAN_PROTOCOL_MASTER_OUT 0x02
#define CAN_PROTOCOL_SLAVE_OUT 0x03
#define CAN_PROTOCOL_TIME_SYNC 0x05

#define CAN_PROTOCOL_GET_LIGHTS 0x00
#define CAN_PROTOCOL_SET_LIGHTS 0x01
#define CAN_PROTOCOL_SET_BRIGHTNESS 0x02
#define CAN_PROTOCOL_GET_TAKEDOWNS 0x03
#define CAN_PROTOCOL_SET_TAKEDOWNS 0x04
#define CAN_PROTOCOL_GET_BRIGHTNESS 0x07
#define CAN_PROTOCOL_READ_PATTERN 0x08
#define CAN_PROTOCOL_WRITE_PATTERN 0x09
#define CAN_PROTOCOL_GET_PATTERN 0x0A
#define CAN_PROTOCOL_SET_PATTERN 0x0B
#define CAN_PROTOCOL_WRITE_PATTERN_STEP 0x0C
#define CAN_PROTOCOL_ENTER_BOOT 0xFD

#define CAN_PROTOCOL_DHCP_DISCOVER 0x00
#define CAN_PROTOCOL_DHCP_OFFER 0x01
#define CAN_PROTOCOL_DHCP_ACK 0x02

// Target light types for brightness controls
#define LIGHT_TYPE_EMERGENCY 0x00
#define LIGHT_TYPE_TAKEDOWNS 0x01
#define LIGHT_TYPE_NIGHT 0x02
#define LIGHT_TYPE_ALL 0xFF

// Bitmask flags for SET_LIGHTS and GET_LIGHTS
#define LIGHT_FLAG_FLASHING 0x01
#define LIGHT_FLAG_NIGHT 0x02
#define LIGHT_FLAG_CRUISE 0x04

// Pattern configuration commands
#define PATTERN_CMD_HEADER 0x00
#define PATTERN_CMD_COMMIT 0x01

// Target memory for pattern storage
#define PATTERN_TARGET_RAM 0x00
#define PATTERN_TARGET_FLASH 0x01

#endif //MAJAK_CANPROTOCOL_H