//
// Created by Matouš Smékal on 04.09.2026.
//

#ifndef MAJAK_CANPROTOCOL_H
#define MAJAK_CANPROTOCOL_H

#define CAN_PROTOCOL_OTA_DATA 0x00
#define CAN_PROTOCOL_SLAVE_OUT 0x01
#define CAN_PROTOCOL_MASTER_OUT 0x02
#define CAN_PROTOCOL_TIME_SYNC 0x02

#define CAN_PROTOCOL_GET_LIGHTS 0x00
#define CAN_PROTOCOL_SET_LIGHTS 0x01
#define CAN_PROTOCOL_SET_BRIGHTNESS 0x02

#endif //MAJAK_CANPROTOCOL_H