/**
 * @file    CanUtils.h
 * @brief   Simple universal CAN transmit/receive library for STM32F103C8T6 (HAL).
 *
 * Features
 * --------
 *  - Send standard (11-bit) or extended (29-bit) data frames.
 *  - Non-blocking receive with an optional user callback.
 *  - One-call filter setup (accept-all or single-ID mask filter).
 *  - Works with the STM32 HAL CAN driver generated by CubeMX.
 *
 * Typical usage
 * -------------
 *  1. Generate CAN peripheral init with CubeMX as usual (hcan).
 *  2. Call CanUtils_Init() once after HAL_CAN_Init().
 *  3. Call CanUtils_Send() anywhere to transmit.
 *  4. (Optional) Register a callback with CanUtils_RegisterRxCallback()
 *     and call CanUtils_Poll() in your main loop to dispatch received frames.
 */

#ifndef CAN_UTILS_H
#define CAN_UTILS_H

#ifdef __cplusplus
extern "C" {

#endif

#include "stm32f1xx_hal.h"
#include <stdint.h>
#include <stdbool.h>
#include "UartUtils.h"

/* -------------------------------------------------------------------------
 * Public types
 * ---------------------------------------------------------------------- */

/** Selects 11-bit or 29-bit CAN identifier. */
typedef enum {
    CAN_ID_STANDARD = 0, /**< Standard frame – 11-bit ID */
    CAN_ID_EXTENDED = 1, /**< Extended frame – 29-bit ID */
} CanIdType;

/** A single CAN frame (data frame only; RTR not supported). */
typedef struct {
    uint32_t id; /**< CAN identifier (11 or 29 bit)        */
    CanIdType idType; /**< Standard or extended                  */
    uint8_t data[8]; /**< Payload bytes                         */
    uint8_t dlc; /**< Data length (0-8)                     */
} CanFrame;

/**
 * Callback invoked by CanUtils_Poll() for every received frame.
 * @param frame  Pointer to the received frame (valid only during the call).
 */
typedef void (*CanUtils_RxCallback)(const CanFrame *frame);

/** Handle that holds all library state. Declare one per CAN peripheral. */
typedef struct {
    CAN_HandleTypeDef *hcan;
    CanUtils_RxCallback rxCallback;
} CanUtilsHandle;

/* -------------------------------------------------------------------------
 * Public API
 * ---------------------------------------------------------------------- */

/**
 * @brief  Initialise the library and start the CAN peripheral.
 *
 * Configures a catch-all receive filter on FIFO 0 and calls HAL_CAN_Start().
 * Call once after MX_CAN_Init().
 *
 * @param  handle  Library handle to initialise.
 * @param  hcan    Pointer to the HAL CAN handle (e.g. &hcan).
 * @retval HAL_OK on success, HAL error code otherwise.
 */
HAL_StatusTypeDef CanUtils_Init(CanUtilsHandle *handle, CAN_HandleTypeDef *hcan);

/**
 * @brief  Configure a 32-bit mask filter on FIFO 0.
 *
 * Accepts frames whose (id & mask) == (filterId & mask).
 * Call after CanUtils_Init() to narrow what the MCU accepts.
 * Pass filterId=0, mask=0 to restore accept-all behaviour.
 *
 * @param  handle    Library handle.
 * @param  filterId  ID to match against (11 or 29-bit value).
 * @param  mask      Bit mask – '1' bits are checked, '0' bits are don't-care.
 * @param  idType    Whether filterId/mask are standard or extended IDs.
 * @retval HAL_OK on success.
 */
HAL_StatusTypeDef CanUtils_SetFilter(CanUtilsHandle *handle,
                                     uint32_t filterId,
                                     uint32_t mask,
                                     CanIdType idType);

/**
 * @brief  Enable debug output to UART.
 * @param  uartHandle  Pointer to an initialised UartUtilsHandle.
 *         Pass NULL to disable debug prints.
 */
void CanUtils_SetDebugUart(UartUtilsHandle *uartHandle);

/**
* @brief  Transmit a CAN frame (blocking until a mailbox is free or timeout).
*
* @param  handle   Library handle.
* @param  frame    Frame to send.
* @param  timeoutMs Maximum time to wait for a free mailbox (ms). Use 0 for
*                   immediate failure if no mailbox is available.
* @retval HAL_OK, HAL_TIMEOUT, or HAL_ERROR.
*/
HAL_StatusTypeDef CanUtils_Send(CanUtilsHandle *handle,
                                const CanFrame *frame,
                                uint32_t timeoutMs);

/**
 * @brief  Register a callback invoked by CanUtils_Poll() for each RX frame.
 *
 * Pass NULL to disable the callback (frames are still dequeued and discarded).
 *
 * @param  handle    Library handle.
 * @param  callback  Function to call on each received frame.
 */
void CanUtils_RegisterRxCallback(CanUtilsHandle *handle, CanUtils_RxCallback callback);

/**
 * @brief  Drain FIFO 0 and dispatch frames to the registered callback.
 *
 * Call this regularly from your main loop (or from the FIFO-pending IRQ).
 * It processes ALL pending messages in one call and returns.
 *
 * @param  handle  Library handle.
 */
void CanUtils_Poll(CanUtilsHandle *handle);

/**
 * @brief  Returns the number of messages currently pending in RX FIFO 0.
 *
 * @param  handle  Library handle.
 * @retval 0-3 pending message count.
 */
uint32_t CanUtils_RxPending(const CanUtilsHandle *handle);
    void CanUtils_PrintError(CAN_HandleTypeDef *hcan);
    /**
 * @brief  Print detailed CAN status (error flags, counters, LEC, transmit status).
 * @param  hcan  CAN handle (can be obtained from handle->hcan).
 */
    void CanUtils_PrintStatus(CAN_HandleTypeDef *hcan);

    /**
     * @brief  Print just the error state (shorter output).
     */
    void CanUtils_PrintError(CAN_HandleTypeDef *hcan);
#ifdef __cplusplus
}
#endif

#endif /* CAN_UTILS_H */
