#!/usr/bin/env python3
"""
generate_calm_lut.py - Look-Up Table generator for Whelen DVI style calm lighting (TOGGLE_CALM).

Generates a precomputed gamma-corrected half-wave sinusoidal look-up table.
- Positive half of sine (0 to pi): scaled by gamma power curve for human visual perception.
- Negative half of sine (pi to 2pi): clamped to 0 (channel is off).
"""

import argparse
import math
import sys
from pathlib import Path


def generate_lut(size: int, gamma: float, max_val: int, active_ratio: float = 0.625) -> list[int]:
    table = []
    for i in range(size):
        fraction = i / size
        if fraction < active_ratio:
            # Active portion: angle goes smoothly from 0 to pi
            angle = math.pi * (fraction / active_ratio)
            sin_val = math.sin(angle)
            # Apply gamma correction to compensate for human eye perception
            corrected = math.pow(sin_val, gamma)
            val = round(corrected * max_val)
            val = max(0, min(max_val, val))
        else:
            # Remainder of cycle: channel is off
            val = 0
        table.append(val)
    return table


def format_c_header(table: list[int], size: int, gamma: float, max_val: int, active_ratio: float) -> str:
    lines = [
        "//",
        "// CalmLut.h - Auto-generated Look-Up Table for TOGGLE_CALM (Whelen DVI)",
        f"// Generated by generate_calm_lut.py (Size: {size}, Gamma: {gamma:.2f}, ActiveRatio: {active_ratio:.3f}, Max: {max_val})",
        "// DO NOT EDIT DIRECTLY - Use scripts/generate_calm_lut.py to re-generate.",
        "//",
        "",
        "#ifndef MAJAK_CALMLUT_H",
        "#define MAJAK_CALMLUT_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define CALM_LUT_SIZE       {size}U",
        f"#define CALM_LUT_MAX_VALUE  {max_val}U",
        "",
        f"static const uint16_t CALM_SINE_LUT[CALM_LUT_SIZE] = {{",
    ]

    cols = 8
    for i in range(0, size, cols):
        chunk = table[i : i + cols]
        entries = ", ".join(f"{v:5d}U" for v in chunk)
        trailing = "," if i + cols < size else ""
        lines.append(f"    {entries}{trailing}")

    lines.extend([
        "};",
        "",
        "#endif // MAJAK_CALMLUT_H",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate gamma-corrected sine LUT for TOGGLE_CALM.")
    parser.add_argument("--size", type=int, default=256, help="Number of entries in LUT (default: 256)")
    parser.add_argument("--gamma", type=float, default=2.2, help="Gamma exponent for human perception (default: 2.2)")
    parser.add_argument(
        "--active-ratio",
        type=float,
        default=0.625,
        help="Active pulse ratio (default: 0.625 for seamless cross-fade with 0 dead time)",
    )
    parser.add_argument("--max-val", type=int, default=65535, help="Peak table value (default: 65535)")
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "CalmLut.h",
        help="Target output C header path",
    )

    args = parser.parse_args()

    table = generate_lut(args.size, args.gamma, args.max_val, args.active_ratio)
    header_content = format_c_header(table, args.size, args.gamma, args.max_val, args.active_ratio)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header_content, encoding="utf-8")
    print(
        f"Successfully generated {args.output} (Size={args.size}, Gamma={args.gamma}, ActiveRatio={args.active_ratio}, Max={args.max_val})"
    )


if __name__ == "__main__":
    main()
